name: codex-ci

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
      - 'web/**'
      - 'docs/**'
      - '.github/workflows/**'
      - 'codex.config.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'api/**'
      - 'web/**'
      - 'docs/**'
      - '.github/workflows/**'
      - 'codex.config.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api:
    name: API (Spring Boot)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Grant execute for gradlew
        run: chmod +x ./gradlew

      - name: Build (without tests)
        run: ./gradlew clean assemble -x test --no-daemon

      - name: Run tests
        run: ./gradlew test --no-daemon

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-reports
          path: |
            api/build/reports/tests/test
            api/build/test-results/test

  web:
    name: Web (Next.js)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            web/package-lock.json
            web/npm-shrinkwrap.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: |
          if [ -f package.json ] && jq -e '.scripts.lint' package.json > /dev/null; then
            npm run lint
          else
            echo "No lint script. Skipping."
          fi

      - name: Unit tests
        run: |
          if [ -f package.json ] && (jq -e '.scripts.test' package.json >/dev/null); then
            npm test -- --ci --reporters=default --reporters=jest-junit || true
          else
            echo "No unit test script. Skipping."
          fi

      - name: Install Playwright (optional)
        run: |
          if [ -f package.json ] && (jq -e '.devDependencies.playwright' package.json >/dev/null || jq -e '.dependencies.playwright' package.json >/dev/null); then
            npx playwright install --with-deps
          else
            echo "Playwright not detected. Skipping browser install."
          fi

      - name: Build
        run: |
          if [ -f package.json ] && jq -e '.scripts.build' package.json >/dev/null; then
            npm run build
          else
            echo "No build script. Skipping."
          fi

      - name: E2E tests (Playwright) - optional
        env:
          CI: true
        run: |
          if [ -f package.json ] && (jq -e '.scripts.e2e' package.json >/dev/null); then
            npm run e2e || true
          else
            echo "No e2e script. Skipping."
          fi

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-playwright-report
          path: |
            web/playwright-report
            web/test-results
          if-no-files-found: ignore
